using RkSoftware.RKPlugin.DependencyInjection.Internals;
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text;

namespace RkSoftware.RKPlugin.DependencyInjection;

public class PluginServiceCollection
{
    object? Services { get; init; }
    static object? GetService(object? obj) => obj?.GetType()?.GetProperty(nameof(Services))?.GetValue(obj);

    internal PluginServiceCollection(object? services)
    {
        this.Services = services;
    }

    // ApplicationEnricherServiceCollectionExtensions
    object? AddServiceLogEnricher() => PluginApplicationEnricherServiceCollection.AddServiceLogEnricher(Services);
    public static object? AddServiceLogEnricher(object? services) => PluginApplicationEnricherServiceCollectionCaller.AddServiceLogEnricher(services);

    object? AddServiceLogEnricher(Action<object?> configure) => PluginApplicationEnricherServiceCollection.AddServiceLogEnricher(Services, configure);
    public static object? AddServiceLogEnricher(object? services, Action<object?> configure) => PluginApplicationEnricherServiceCollectionCaller.AddServiceLogEnricher(services, configure);

    object? AddServiceLogEnricher_(object? section) => PluginApplicationEnricherServiceCollection.AddServiceLogEnricher_(Services, section);
    public static object? AddServiceLogEnricher_(object? services, object? section) => PluginApplicationEnricherServiceCollectionCaller.AddServiceLogEnricher_(services, section);

    //
    object? AddHttpClient() => PluginHttpClientFactoryServiceCollection.AddHttpClient(Services);
    public static object? AddHttpClient(object? services) => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient(services);
    object? ConfigureHttpClientDefaults(Action<object?> configure) => PluginHttpClientFactoryServiceCollection.ConfigureHttpClientDefaults(Services, configure);
    public static object? ConfigureHttpClientDefaults(object? services, Action<object?> configure) => PluginHttpClientFactoryServiceCollectionCaller.ConfigureHttpClientDefaults(services, configure);
    object? AddHttpClient(string name) => PluginHttpClientFactoryServiceCollection.AddHttpClient(Services, name);
    public static object? AddHttpClient(object? services, string name) => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient(services, name);
    object? AddHttpClient(string name, Action<HttpClient> configureClient) => PluginHttpClientFactoryServiceCollection.AddHttpClient(Services, name, configureClient);
    public static object? AddHttpClient(object? services, string name, Action<HttpClient> configureClient) => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient(services, name, configureClient);
    object? AddHttpClient(string name, Action<IServiceProvider, HttpClient> configureClient) => PluginHttpClientFactoryServiceCollection.AddHttpClient(Services, name, configureClient);
    public static object? AddHttpClient(object? services, string name, Action<IServiceProvider, HttpClient> configureClient) => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient(services, name, configureClient);
    object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>() where TClient : class => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient>(Services);
    public static object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(object? services) where TClient : class => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient>(services);
    object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>() where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient, TImplementation>(Services);
    public static object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(object? services) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient, TImplementation>(services);
    object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(string name) where TClient : class => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient>(Services, name);
    public static object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(object? services, string name) where TClient : class => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient>(services, name);
    object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(string name) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient, TImplementation>(Services, name);
    public static object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(object? services, string name) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient, TImplementation>(services, name);
    object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(Action<HttpClient> configureClient) where TClient : class => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient>(Services, configureClient);
    public static object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(object? services, Action<HttpClient> configureClient) where TClient : class => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient>(services, configureClient);
    object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(Action<IServiceProvider, HttpClient> configureClient) where TClient : class => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient>(Services, configureClient);
    public static object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(object? services, Action<IServiceProvider, HttpClient> configureClient) where TClient : class => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient>(services, configureClient);
    object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(Action<HttpClient> configureClient) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient, TImplementation>(Services, configureClient);
    public static object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(object? services, Action<HttpClient> configureClient) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient, TImplementation>(services, configureClient);
    object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(Action<IServiceProvider, HttpClient> configureClient) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient, TImplementation>(Services, configureClient);
    public static object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(object? services, Action<IServiceProvider, HttpClient> configureClient) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient, TImplementation>(services, configureClient);
    object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(string name, Action<HttpClient> configureClient) where TClient : class => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient>(Services, name, configureClient);
    public static object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(object? services, string name, Action<HttpClient> configureClient) where TClient : class => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient>(services, name, configureClient);
    object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(string name, Action<IServiceProvider, HttpClient> configureClient) where TClient : class => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient>(Services, name, configureClient);
    public static object? AddHttpClient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TClient>(object? services, string name, Action<IServiceProvider, HttpClient> configureClient) where TClient : class => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient>(services, name, configureClient);
    object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(string name, Action<HttpClient> configureClient) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient, TImplementation>(Services, name, configureClient);
    public static object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(object? services, string name, Action<HttpClient> configureClient) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient, TImplementation>(services, name, configureClient);
    object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(string name, Action<IServiceProvider, HttpClient> configureClient) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient, TImplementation>(Services, name, configureClient);
    public static object? AddHttpClient<TClient, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(object? services, string name, Action<IServiceProvider, HttpClient> configureClient) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient, TImplementation>(services, name, configureClient);
    object? AddHttpClient<TClient, TImplementation>(Func<HttpClient, TImplementation> factory) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient, TImplementation>(Services, factory);
    public static object? AddHttpClient<TClient, TImplementation>(object? services, Func<HttpClient, TImplementation> factory) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient, TImplementation>(services, factory);
    object? AddHttpClient<TClient, TImplementation>(string name, Func<HttpClient, TImplementation> factory) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient, TImplementation>(Services, name, factory);
    public static object? AddHttpClient<TClient, TImplementation>(object? services, string name, Func<HttpClient, TImplementation> factory) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient, TImplementation>(services, name, factory);
    object? AddHttpClient<TClient, TImplementation>(Func<HttpClient, IServiceProvider, TImplementation> factory) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient, TImplementation>(Services, factory);
    public static object? AddHttpClient<TClient, TImplementation>(object? services, Func<HttpClient, IServiceProvider, TImplementation> factory) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient, TImplementation>(services, factory);
    object? AddHttpClient<TClient, TImplementation>(string name, Func<HttpClient, IServiceProvider, TImplementation> factory) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollection.AddHttpClient<TClient, TImplementation>(Services, name, factory);
    public static object? AddHttpClient<TClient, TImplementation>(object? services, string name, Func<HttpClient, IServiceProvider, TImplementation> factory) where TClient : class where TImplementation : class, TClient => PluginHttpClientFactoryServiceCollectionCaller.AddHttpClient<TClient, TImplementation>(services, name, factory);
    object? AddTransient(Type serviceType, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type implementationType) => PluginServiceCollectionService.AddTransient(Services, serviceType, implementationType);
    public static object? AddTransient(object? services, Type serviceType, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type implementationType) => PluginServiceCollectionServiceCaller.AddTransient(services, serviceType, implementationType);
    object? AddTransient(Type serviceType, Func<IServiceProvider, object> implementationFactory) => PluginServiceCollectionService.AddTransient(Services, serviceType, implementationFactory);
    public static object? AddTransient(object? services, Type serviceType, Func<IServiceProvider, object> implementationFactory) => PluginServiceCollectionServiceCaller.AddTransient(services, serviceType, implementationFactory);
    object? AddTransient<TService, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>() where TService : class where TImplementation : class, TService => PluginServiceCollectionService.AddTransient<TService, TImplementation>(Services);
    public static object? AddTransient<TService, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(object? services) where TService : class where TImplementation : class, TService => PluginServiceCollectionServiceCaller.AddTransient<TService, TImplementation>(services);
    object? AddTransient([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type serviceType) => PluginServiceCollectionService.AddTransient(Services, serviceType);
    public static object? AddTransient(object? services, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type serviceType) => PluginServiceCollectionServiceCaller.AddTransient(services, serviceType);
    object? AddTransient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TService>() where TService : class => PluginServiceCollectionService.AddTransient<TService>(Services);
    public static object? AddTransient<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TService>(object? services) where TService : class => PluginServiceCollectionServiceCaller.AddTransient<TService>(services);
    object? AddTransient<TService>(Func<IServiceProvider, TService> implementationFactory) where TService : class => PluginServiceCollectionService.AddTransient<TService>(Services, implementationFactory);
    public static object? AddTransient<TService>(object? services, Func<IServiceProvider, TService> implementationFactory) where TService : class => PluginServiceCollectionServiceCaller.AddTransient<TService>(services, implementationFactory);
    object? AddTransient<TService, TImplementation>(Func<IServiceProvider, TImplementation> implementationFactory) where TService : class where TImplementation : class, TService => PluginServiceCollectionService.AddTransient<TService, TImplementation>(Services, implementationFactory);
    public static object? AddTransient<TService, TImplementation>(object? services, Func<IServiceProvider, TImplementation> implementationFactory) where TService : class where TImplementation : class, TService => PluginServiceCollectionServiceCaller.AddTransient<TService, TImplementation>(services, implementationFactory);
    object? AddScoped(Type serviceType, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type implementationType) => PluginServiceCollectionService.AddScoped(Services, serviceType, implementationType);
    public static object? AddScoped(object? services, Type serviceType, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type implementationType) => PluginServiceCollectionServiceCaller.AddScoped(services, serviceType, implementationType);
    object? AddScoped(Type serviceType, Func<IServiceProvider, object> implementationFactory) => PluginServiceCollectionService.AddScoped(Services, serviceType, implementationFactory);
    public static object? AddScoped(object? services, Type serviceType, Func<IServiceProvider, object> implementationFactory) => PluginServiceCollectionServiceCaller.AddScoped(services, serviceType, implementationFactory);
    object? AddScoped<TService, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>() where TService : class where TImplementation : class, TService => PluginServiceCollectionService.AddScoped<TService, TImplementation>(Services);
    public static object? AddScoped<TService, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(object? services) where TService : class where TImplementation : class, TService => PluginServiceCollectionServiceCaller.AddScoped<TService, TImplementation>(services);
    object? AddScoped([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type serviceType) => PluginServiceCollectionService.AddScoped(Services, serviceType);
    public static object? AddScoped(object? services, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type serviceType) => PluginServiceCollectionServiceCaller.AddScoped(services, serviceType);
    object? AddScoped<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TService>() where TService : class => PluginServiceCollectionService.AddScoped<TService>(Services);
    public static object? AddScoped<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TService>(object? services) where TService : class => PluginServiceCollectionServiceCaller.AddScoped<TService>(services);
    object? AddScoped<TService>(Func<IServiceProvider, TService> implementationFactory) where TService : class => PluginServiceCollectionService.AddScoped(Services, implementationFactory);
    public static object? AddScoped<TService>(object? services, Func<IServiceProvider, TService> implementationFactory) where TService : class => PluginServiceCollectionServiceCaller.AddScoped(services, implementationFactory);
    object? AddScoped<TService, TImplementation>(Func<IServiceProvider, TImplementation> implementationFactory) where TService : class where TImplementation : class, TService => PluginServiceCollectionService.AddScoped<TService, TImplementation>(Services, implementationFactory);
    public static object? AddScoped<TService, TImplementation>(object? services, Func<IServiceProvider, TImplementation> implementationFactory) where TService : class where TImplementation : class, TService => PluginServiceCollectionServiceCaller.AddScoped<TService, TImplementation>(services, implementationFactory);
    object? AddSingleton(Type serviceType, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type implementationType) => PluginServiceCollectionService.AddSingleton(Services, serviceType, implementationType);
    public static object? AddSingleton(object? services, Type serviceType, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type implementationType) => PluginServiceCollectionServiceCaller.AddSingleton(services, serviceType, implementationType);
    object? AddSingleton(Type serviceType, Func<IServiceProvider, object> implementationFactory) => PluginServiceCollectionService.AddSingleton(Services, serviceType, implementationFactory);
    public static object? AddSingleton(object? services, Type serviceType, Func<IServiceProvider, object> implementationFactory) => PluginServiceCollectionServiceCaller.AddSingleton(services, serviceType, implementationFactory);
    object? AddSingleton<TService, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>() where TService : class where TImplementation : class, TService => PluginServiceCollectionService.AddSingleton<TService, TImplementation>(Services);
    public static object? AddSingleton<TService, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TImplementation>(object? services) where TService : class where TImplementation : class, TService => PluginServiceCollectionServiceCaller.AddSingleton<TService, TImplementation>(services);
    object? AddSingleton([DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type serviceType) => PluginServiceCollectionService.AddSingleton(Services, serviceType);
    public static object? AddSingleton(object? services, [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] Type serviceType) => PluginServiceCollectionServiceCaller.AddSingleton(services, serviceType);
    object? AddSingleton<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TService>() where TService : class => PluginServiceCollectionService.AddSingleton<TService>(Services);
    public static object? AddSingleton<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors)] TService>(object? services) where TService : class => PluginServiceCollectionServiceCaller.AddSingleton<TService>(services);
    object? AddSingleton<TService>(Func<IServiceProvider, TService> implementationFactory) where TService : class => PluginServiceCollectionService.AddSingleton<TService>(Services, implementationFactory);
    public static object? AddSingleton<TService>(object? services, Func<IServiceProvider, TService> implementationFactory) where TService : class => PluginServiceCollectionServiceCaller.AddSingleton<TService>(services, implementationFactory);
    object? AddSingleton<TService, TImplementation>(Func<IServiceProvider, TImplementation> implementationFactory) where TService : class where TImplementation : class, TService => PluginServiceCollectionService.AddSingleton<TService, TImplementation>(Services, implementationFactory);
    public static object? AddSingleton<TService, TImplementation>(object? services, Func<IServiceProvider, TImplementation> implementationFactory) where TService : class where TImplementation : class, TService => PluginServiceCollectionServiceCaller.AddSingleton<TService, TImplementation>(services, implementationFactory);
    object? AddSingleton(Type serviceType, object implementationInstance) => PluginServiceCollectionService.AddSingleton(Services, serviceType, implementationInstance);
    public static object? AddSingleton(object? services, Type serviceType, object implementationInstance) => PluginServiceCollectionServiceCaller.AddSingleton(services, serviceType, implementationInstance);
    object? AddSingleton<TService>(TService implementationInstance) where TService : class => PluginServiceCollectionService.AddSingleton<TService>(Services, implementationInstance);
    public static object? AddSingleton<TService>(object? services, TService implementationInstance) where TService : class => PluginServiceCollectionServiceCaller.AddSingleton<TService>(services, implementationInstance);
}
