using Microsoft.Extensions.Caching.SqlServer;
using Microsoft.Extensions.Caching.StackExchangeRedis;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Diagnostics.Metrics;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Http.Diagnostics;
using Microsoft.Extensions.ObjectPool;
using RkSoftware.RKPlugin;
using System.Diagnostics;
using System.Reflection;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
var services = builder.Services;

var pluginPath = Path.Combine(Assembly.GetEntryAssembly()?.Location!, "../../../../../TestPlugin/bin/Debug/net10.0");
var plugins = PluginLoadContext.LoadExtensions(pluginPath);
foreach (var plugin in plugins)
    foreach (var assembly in plugin.Assemblies)
        foreach (var type in assembly.GetTypes())
        {
            var method = type.GetMethod("ConfigureServices");
            if (method != null)
            {
                var result = PluginLoadContext.Invoke(services, method, null, null);
                Debug.Write(result);
            }
        }

services.AddRazorPages();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

app.UseHttpsRedirection();

app.UseRouting();

app.UseAuthorization();

app.MapStaticAssets();
app.MapRazorPages()
   .WithStaticAssets();

app.Run();


#region
/*
ServiceCollectionDescriptorExtensions.Add(IServiceCollection, ServiceDescriptor);
ServiceCollectionDescriptorExtensions.Add(IServiceCollection, IEnumerable<ServiceDescriptor>);
ServiceCollectionDescriptorExtensions.RemoveAll(IServiceCollection, Type);
ServiceCollectionDescriptorExtensions.RemoveAll<T>(IServiceCollection);
ServiceCollectionDescriptorExtensions.RemoveAllKeyed(IServiceCollection, Type, Object)
ServiceCollectionDescriptorExtensions.RemoveAllKeyed<T>(IServiceCollection, Object)
ServiceCollectionDescriptorExtensions.Replace(IServiceCollection, ServiceDescriptor)
ServiceCollectionDescriptorExtensions.TryAdd(IServiceCollection, ServiceDescriptor)
ServiceCollectionDescriptorExtensions.TryAdd(IServiceCollection, IEnumerable<ServiceDescriptor>)
ServiceCollectionDescriptorExtensions.TryAddEnumerable(IServiceCollection, ServiceDescriptor)
ServiceCollectionDescriptorExtensions.TryAddEnumerable(IServiceCollection, IEnumerable<ServiceDescriptor>)
ServiceCollectionDescriptorExtensions.TryAddKeyedScoped(IServiceCollection, Type, Object)
ServiceCollectionDescriptorExtensions.TryAddKeyedScoped(IServiceCollection, Type, Object, Func<IServiceProvider, Object, Object>)
ServiceCollectionDescriptorExtensions.TryAddKeyedScoped(IServiceCollection, Type, Object, Type)
ServiceCollectionDescriptorExtensions.TryAddKeyedScoped<TService>(IServiceCollection, Object)
ServiceCollectionDescriptorExtensions.TryAddKeyedScoped<TService>(IServiceCollection, Object, Func<IServiceProvider, Object, TService>)
ServiceCollectionDescriptorExtensions.TryAddKeyedScoped<TService, TImplementation>(IServiceCollection, Object)
ServiceCollectionDescriptorExtensions.TryAddKeyedSingleton(IServiceCollection, Type, Object)
ServiceCollectionDescriptorExtensions.TryAddKeyedSingleton(IServiceCollection, Type, Object, Func<IServiceProvider, Object, Object>)
ServiceCollectionDescriptorExtensions.TryAddKeyedSingleton(IServiceCollection, Type, Object, Type)
ServiceCollectionDescriptorExtensions.TryAddKeyedSingleton<TService>(IServiceCollection, Object)
ServiceCollectionDescriptorExtensions.TryAddKeyedSingleton<TService>(IServiceCollection, Object, TService)
ServiceCollectionDescriptorExtensions.TryAddKeyedSingleton<TService>(IServiceCollection, Object, Func<IServiceProvider, Object, TService>)
ServiceCollectionDescriptorExtensions.TryAddKeyedSingleton<TService, TImplementation>(IServiceCollection, Object)
ServiceCollectionDescriptorExtensions.TryAddKeyedTransient(IServiceCollection, Type, Object)
ServiceCollectionDescriptorExtensions.TryAddKeyedTransient(IServiceCollection, Type, Object, Func<IServiceProvider, Object, Object>)
ServiceCollectionDescriptorExtensions.TryAddKeyedTransient(IServiceCollection, Type, Object, Type)
ServiceCollectionDescriptorExtensions.TryAddKeyedTransient<TService>(IServiceCollection, Object)
ServiceCollectionDescriptorExtensions.TryAddKeyedTransient<TService>(IServiceCollection, Object, Func<IServiceProvider, Object, TService>)
ServiceCollectionDescriptorExtensions.TryAddKeyedTransient<TService, TImplementation>(IServiceCollection, Object)
ServiceCollectionDescriptorExtensions.TryAddScoped(IServiceCollection, Type)
ServiceCollectionDescriptorExtensions.TryAddScoped(IServiceCollection, Type, Func<IServiceProvider, Object>)
ServiceCollectionDescriptorExtensions.TryAddScoped(IServiceCollection, Type, Type)
ServiceCollectionDescriptorExtensions.TryAddScoped<TService>(IServiceCollection)
ServiceCollectionDescriptorExtensions.TryAddScoped<TService>(IServiceCollection, Func<IServiceProvider, TService>)
ServiceCollectionDescriptorExtensions.TryAddScoped<TService, TImplementation>(IServiceCollection)
ServiceCollectionDescriptorExtensions.TryAddSingleton(IServiceCollection, Type)
ServiceCollectionDescriptorExtensions.TryAddSingleton(IServiceCollection, Type, Func<IServiceProvider, Object>)
ServiceCollectionDescriptorExtensions.TryAddSingleton(IServiceCollection, Type, Type)
ServiceCollectionDescriptorExtensions.TryAddSingleton<TService>(IServiceCollection)
ServiceCollectionDescriptorExtensions.TryAddSingleton<TService>(IServiceCollection, TService)
ServiceCollectionDescriptorExtensions.TryAddSingleton<TService>(IServiceCollection, Func<IServiceProvider, TService>)
ServiceCollectionDescriptorExtensions.TryAddSingleton<TService, TImplementation>(IServiceCollection)
ServiceCollectionDescriptorExtensions.TryAddTransient(IServiceCollection, Type)
ServiceCollectionDescriptorExtensions.TryAddTransient(IServiceCollection, Type, Func<IServiceProvider, Object>)
ServiceCollectionDescriptorExtensions.TryAddTransient(IServiceCollection, Type, Type)
ServiceCollectionDescriptorExtensions.TryAddTransient<TService>(IServiceCollection)
ServiceCollectionDescriptorExtensions.TryAddTransient<TService>(IServiceCollection, Func<IServiceProvider, TService>)
ServiceCollectionDescriptorExtensions.TryAddTransient<TService, TImplementation>(IServiceCollection)
FakeLoggerServiceCollectionExtensions.AddFakeLogging(IServiceCollection)
FakeLoggerServiceCollectionExtensions.AddFakeLogging(IServiceCollection, IConfigurationSection)
FakeLoggerServiceCollectionExtensions.AddFakeLogging(IServiceCollection, Action<FakeLogCollectorOptions>)
FakeRedactionServiceCollectionExtensions.AddFakeRedaction(IServiceCollection)
FakeRedactionServiceCollectionExtensions.AddFakeRedaction(IServiceCollection, Action<FakeRedactorOptions>)
HealthCheckServiceCollectionExtensions.AddHealthChecks(IServiceCollection)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient(IServiceCollection)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient(IServiceCollection, String)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient(IServiceCollection, String, Action<IServiceProvider, HttpClient>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient(IServiceCollection, String, Action<HttpClient>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient>(IServiceCollection)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient>(IServiceCollection, Action<IServiceProvider, HttpClient>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient>(IServiceCollection, Action<HttpClient>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient>(IServiceCollection, String)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient>(IServiceCollection, String, Action<IServiceProvider, HttpClient>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient>(IServiceCollection, String, Action<HttpClient>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient, TImplementation>(IServiceCollection)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient, TImplementation>(IServiceCollection, Action<IServiceProvider, HttpClient>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient, TImplementation>(IServiceCollection, Action<HttpClient>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient,TImplementation>(IServiceCollection, Func<HttpClient,TImplementation>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient,TImplementation>(IServiceCollection, Func<HttpClient,IServiceProvider,TImplementation>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient,TImplementation>(IServiceCollection, String)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient,TImplementation>(IServiceCollection, String, Action<IServiceProvider,HttpClient>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient,TImplementation>(IServiceCollection, String, Action<HttpClient>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient,TImplementation>(IServiceCollection, String, Func<HttpClient,TImplementation>)
HttpClientFactoryServiceCollectionExtensions.AddHttpClient<TClient,TImplementation>(IServiceCollection, String, Func<HttpClient,IServiceProvider,TImplementation>)
HttpClientFactoryServiceCollectionExtensions.ConfigureHttpClientDefaults(IServiceCollection, Action<IHttpClientBuilder>);
HttpClientLatencyTelemetryExtensions.AddHttpClientLatencyTelemetry(IServiceCollection)
HttpClientLatencyTelemetryExtensions.AddHttpClientLatencyTelemetry(IServiceCollection, IConfigurationSection)
HttpClientLatencyTelemetryExtensions.AddHttpClientLatencyTelemetry(IServiceCollection, Action<HttpClientLatencyTelemetryOptions>)
HttpClientLoggingServiceCollectionExtensions.AddExtendedHttpClientLogging(IServiceCollection)
HttpClientLoggingServiceCollectionExtensions.AddExtendedHttpClientLogging(IServiceCollection, IConfigurationSection)
HttpClientLoggingServiceCollectionExtensions.AddExtendedHttpClientLogging(IServiceCollection, Action<LoggingOptions>)
HttpClientLoggingServiceCollectionExtensions.AddHttpClientLogEnricher<T>(IServiceCollection)
HttpDiagnosticsServiceCollectionExtensions.AddDownstreamDependencyMetadata(IServiceCollection, IDownstreamDependencyMetadata)
HttpDiagnosticsServiceCollectionExtensions.AddDownstreamDependencyMetadata<T>(IServiceCollection)
HybridCacheServiceExtensions.AddHybridCache(IServiceCollection)
HybridCacheServiceExtensions.AddHybridCache(IServiceCollection, Action<HybridCacheOptions>)
KubernetesProbesExtensions.AddKubernetesProbes(IServiceCollection)
KubernetesProbesExtensions.AddKubernetesProbes(IServiceCollection, IConfigurationSection)
KubernetesProbesExtensions.AddKubernetesProbes(IServiceCollection, Action<KubernetesProbesOptions>)
KubernetesProbesExtensions.AddConsoleLatencyDataExporter(IServiceCollection)
LatencyConsoleExtensions.AddConsoleLatencyDataExporter(IServiceCollection, IConfigurationSection)
LatencyConsoleExtensions.AddConsoleLatencyDataExporter(IServiceCollection, Action<LatencyConsoleOptions>)
LatencyContextExtensions.AddLatencyContext(IServiceCollection)
LatencyContextExtensions.AddLatencyContext(IServiceCollection, IConfigurationSection)
LatencyContextExtensions.AddLatencyContext(IServiceCollection, Action<LatencyContextOptions>)
LatencyRegistryServiceCollectionExtensions.RegisterCheckpointNames(IServiceCollection, String[])
LatencyRegistryServiceCollectionExtensions.RegisterMeasureNames(IServiceCollection, String[])
LatencyRegistryServiceCollectionExtensions.RegisterTagNames(IServiceCollection, String[])
LocalizationServiceCollectionExtensions.AddLocalization(IServiceCollection)
LocalizationServiceCollectionExtensions.AddLocalization(IServiceCollection, Action<LocalizationOptions>)
LoggingServiceCollectionExtensions.AddLogging(IServiceCollection)
LoggingServiceCollectionExtensions.AddLogging(IServiceCollection, Action<ILoggingBuilder>)
MemoryCacheServiceCollectionExtensions.AddDistributedMemoryCache(IServiceCollection)
MemoryCacheServiceCollectionExtensions.AddDistributedMemoryCache(IServiceCollection, Action<MemoryDistributedCacheOptions>)
MemoryCacheServiceCollectionExtensions.AddMemoryCache(IServiceCollection)
MemoryCacheServiceCollectionExtensions.AddMemoryCache(IServiceCollection, Action<MemoryCacheOptions>)
MemoryCacheServiceCollectionExtensions.AddMetrics(IServiceCollection)
MetricsServiceExtensions.AddMetrics(IServiceCollection, Action<IMetricsBuilder>)
NullLatencyContextServiceCollectionExtensions.AddNullLatencyContext(IServiceCollection)
ObjectPoolServiceCollectionExtensions.AddPooled<TService>(IServiceCollection, Action<DependencyInjectionPoolOptions>)
ObjectPoolServiceCollectionExtensions.AddPooled<TService,TImplementation>(IServiceCollection, Action<DependencyInjectionPoolOptions>)
ObjectPoolServiceCollectionExtensions.ConfigurePool<TService>(IServiceCollection, Action<DependencyInjectionPoolOptions>)
ObjectPoolServiceCollectionExtensions.ConfigurePools(IServiceCollection, IConfigurationSection)
OptionsConfigurationServiceCollectionExtensions.Configure<TOptions>(IServiceCollection, IConfiguration)
OptionsConfigurationServiceCollectionExtensions.Configure<TOptions>(IServiceCollection, IConfiguration, Action<BinderOptions>)
OptionsConfigurationServiceCollectionExtensions.Configure<TOptions>(IServiceCollection, String, IConfiguration)
OptionsConfigurationServiceCollectionExtensions.Configure<TOptions>(IServiceCollection, String, IConfiguration, Action<BinderOptions>)
OptionsConfigurationServiceCollectionExtensions.AddOptions(IServiceCollection)
OptionsServiceCollectionExtensions.AddOptions<TOptions>(IServiceCollection)
OptionsServiceCollectionExtensions.AddOptions<TOptions>(IServiceCollection, String)
OptionsServiceCollectionExtensions.AddOptionsWithValidateOnStart<TOptions>(IServiceCollection, String)
OptionsServiceCollectionExtensions.AddOptionsWithValidateOnStart<TOptions,TValidateOptions>(IServiceCollection, String)
OptionsServiceCollectionExtensions.Configure<TOptions>(IServiceCollection, Action<TOptions>)
OptionsServiceCollectionExtensions.Configure<TOptions>(IServiceCollection, String, Action<TOptions>)
OptionsServiceCollectionExtensions.ConfigureAll<TOptions>(IServiceCollection, Action<TOptions>)
OptionsServiceCollectionExtensions.ConfigureOptions(IServiceCollection, Object)
OptionsServiceCollectionExtensions.ConfigureOptions(IServiceCollection, Type)
OptionsServiceCollectionExtensions.ConfigureOptions<TConfigureOptions>(IServiceCollection)
OptionsServiceCollectionExtensions.PostConfigure<TOptions>(IServiceCollection, Action<TOptions>)
OptionsServiceCollectionExtensions.PostConfigure<TOptions>(IServiceCollection, String, Action<TOptions>)
OptionsServiceCollectionExtensions.PostConfigureAll<TOptions>(IServiceCollection, Action<TOptions>)
ProcessEnricherServiceCollectionExtensions.AddProcessLogEnricher(IServiceCollection)
ProcessEnricherServiceCollectionExtensions.AddProcessLogEnricher(IServiceCollection, IConfigurationSection)
ProcessEnricherServiceCollectionExtensions.AddProcessLogEnricher(IServiceCollection, Action<ProcessLogEnricherOptions>)
RedactionServiceCollectionExtensions.AddRedaction(IServiceCollection)
RedactionServiceCollectionExtensions.AddRedaction(IServiceCollection, Action<IRedactionBuilder>)
ResilienceServiceCollectionExtensions.AddResilienceEnricher(IServiceCollection)
ResourceMonitoringServiceCollectionExtensions.AddResourceMonitoring(IServiceCollection)
ResourceMonitoringServiceCollectionExtensions.AddResourceMonitoring(IServiceCollection, Action<IResourceMonitorBuilder>)
ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection)
ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection, ServiceProviderOptions)
ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection, Boolean)
ServiceCollectionHostedServiceExtensions.AddHostedService<THostedService>(IServiceCollection)
ServiceCollectionHostedServiceExtensions.AddHostedService<THostedService>(IServiceCollection, Func<IServiceProvider,THostedService>)
ServiceCollectionHostedServiceExtensions.AddKeyedScoped(IServiceCollection, Type, Object)
ServiceCollectionServiceExtensions.AddKeyedScoped(IServiceCollection, Type, Object, Func<IServiceProvider,Object,Object>)
ServiceCollectionServiceExtensions.AddKeyedScoped(IServiceCollection, Type, Object, Type)
ServiceCollectionServiceExtensions.AddKeyedScoped<TService>(IServiceCollection, Object)
ServiceCollectionServiceExtensions.AddKeyedScoped<TService>(IServiceCollection, Object, Func<IServiceProvider,Object,TService>)
ServiceCollectionServiceExtensions.AddKeyedScoped<TService,TImplementation>(IServiceCollection, Object)
ServiceCollectionServiceExtensions.AddKeyedScoped<TService,TImplementation>(IServiceCollection, Object, Func<IServiceProvider,Object,TImplementation>)
ServiceCollectionServiceExtensions.AddKeyedSingleton(IServiceCollection, Type, Object)
ServiceCollectionServiceExtensions.AddKeyedSingleton(IServiceCollection, Type, Object, Func<IServiceProvider,Object,Object>)
ServiceCollectionServiceExtensions.AddKeyedSingleton(IServiceCollection, Type, Object, Object)
ServiceCollectionServiceExtensions.AddKeyedSingleton(IServiceCollection, Type, Object, Type)
ServiceCollectionServiceExtensions.AddKeyedSingleton<TService>(IServiceCollection, Object)
ServiceCollectionServiceExtensions.AddKeyedSingleton<TService>(IServiceCollection, Object, TService)
ServiceCollectionServiceExtensions.AddKeyedSingleton<TService>(IServiceCollection, Object, Func<IServiceProvider,Object,TService>)
ServiceCollectionServiceExtensions.AddKeyedSingleton<TService,TImplementation>(IServiceCollection, Object)
ServiceCollectionServiceExtensions.AddKeyedSingleton<TService,TImplementation>(IServiceCollection, Object, Func<IServiceProvider,Object,TImplementation>)
ServiceCollectionServiceExtensions.AddKeyedTransient(IServiceCollection, Type, Object)
ServiceCollectionServiceExtensions.AddKeyedTransient(IServiceCollection, Type, Object, Func<IServiceProvider,Object,Object>)
ServiceCollectionServiceExtensions.AddKeyedTransient(IServiceCollection, Type, Object, Type)
ServiceCollectionServiceExtensions.AddKeyedTransient<TService>(IServiceCollection, Object)
ServiceCollectionServiceExtensions.AddKeyedTransient<TService>(IServiceCollection, Object, Func<IServiceProvider,Object,TService>)
ServiceCollectionServiceExtensions.AddKeyedTransient<TService,TImplementation>(IServiceCollection, Object)
ServiceCollectionServiceExtensions.AddKeyedTransient<TService,TImplementation>(IServiceCollection, Object, Func<IServiceProvider,Object,TImplementation>)
ServiceCollectionServiceExtensions.AddScoped(IServiceCollection, Type)
ServiceCollectionServiceExtensions.AddScoped(IServiceCollection, Type, Func<IServiceProvider,Object>)
ServiceCollectionServiceExtensions.AddScoped(IServiceCollection, Type, Type)
ServiceCollectionServiceExtensions.AddScoped<TService>(IServiceCollection)
ServiceCollectionServiceExtensions.AddScoped<TService>(IServiceCollection, Func<IServiceProvider,TService>)
ServiceCollectionServiceExtensions.AddScoped<TService,TImplementation>(IServiceCollection)
ServiceCollectionServiceExtensions.AddScoped<TService,TImplementation>(IServiceCollection, Func<IServiceProvider,TImplementation>)
ServiceCollectionServiceExtensions.AddSingleton(IServiceCollection, Type)
ServiceCollectionServiceExtensions.AddSingleton(IServiceCollection, Type, Func<IServiceProvider,Object>)
ServiceCollectionServiceExtensions.AddSingleton(IServiceCollection, Type, Object)
ServiceCollectionServiceExtensions.AddSingleton(IServiceCollection, Type, Type)
ServiceCollectionServiceExtensions.AddSingleton<TService>(IServiceCollection)
ServiceCollectionServiceExtensions.AddSingleton<TService>(IServiceCollection, TService)
ServiceCollectionServiceExtensions.AddSingleton<TService>(IServiceCollection, Func<IServiceProvider,TService>)
ServiceCollectionServiceExtensions.AddSingleton<TService,TImplementation>(IServiceCollection)
ServiceCollectionServiceExtensions.AddSingleton<TService,TImplementation>(IServiceCollection, Func<IServiceProvider,TImplementation>)
ServiceCollectionServiceExtensions.AddTransient(IServiceCollection, Type)
ServiceCollectionServiceExtensions.AddTransient(IServiceCollection, Type, Func<IServiceProvider,Object>)
ServiceCollectionServiceExtensions.AddTransient(IServiceCollection, Type, Type)
ServiceCollectionServiceExtensions.AddTransient<TService>(IServiceCollection)
ServiceCollectionServiceExtensions.AddTransient<TService>(IServiceCollection, Func<IServiceProvider,TService>)
ServiceCollectionServiceExtensions.AddTransient<TService,TImplementation>(IServiceCollection)
ServiceCollectionServiceExtensions.AddTransient<TService,TImplementation>(IServiceCollection, Func<IServiceProvider,TImplementation>)
SqlServerCachingServicesExtensions.AddDistributedSqlServerCache(IServiceCollection, Action<SqlServerCacheOptions>)
StackExchangeRedisCacheServiceCollectionExtensions.AddStackExchangeRedisCache(IServiceCollection, Action<RedisCacheOptions>)
TcpEndpointProbesExtensions.AddTcpEndpointProbe(IServiceCollection)
TcpEndpointProbesExtensions.AddTcpEndpointProbe(IServiceCollection, IConfigurationSection)
TcpEndpointProbesExtensions.AddTcpEndpointProbe(IServiceCollection, Action<TcpEndpointProbesOptions>)
TcpEndpointProbesExtensions.AddTcpEndpointProbe(IServiceCollection, String)
TcpEndpointProbesExtensions.AddTcpEndpointProbe(IServiceCollection, String, IConfigurationSection)
TcpEndpointProbesExtensions.AddTcpEndpointProbe(IServiceCollection, String, Action<TcpEndpointProbesOptions>)
SystemdHostBuilderExtensions.AddSystemd(IServiceCollection)
WindowsServiceLifetimeHostBuilderExtensions.AddWindowsService(IServiceCollection)
WindowsServiceLifetimeHostBuilderExtensions.AddWindowsService(IServiceCollection, Action<WindowsServiceLifetimeOptions>)	
*/
#endregion